### ISSUE TITLE
Highlights put word/s on new line

### ISSUE THREAD

**Issue by linuxlite** [michael-milette/highlightjs#6]
What the page normally looks like:

![highlight1a](https://user-images.githubusercontent.com/5382578/28254249-31a988b2-6aff-11e7-8126-fcbea4b88f17.png)

What the page looks like after highlight.js results:

![highlight1](https://user-images.githubusercontent.com/5382578/28254259-4b031850-6aff-11e7-9a44-15dcac4ce415.png)

**Comment by linuxlite** [comment]
FYI - my fix was to use:

`            wrap: 'ignore',`

in highlight.js line 692 which produces exactly what I want:

![screenshot_2017-07-17_15-42-47](https://user-images.githubusercontent.com/5382578/28255048-a516eda6-6b06-11e7-9e71-46aff49bf154.png)

is this the correct solution?

**Comment by michael-milette** [comment]
Hi @linuxlite ,

I am not sure how setting wrap to 'ignore' fixed your issues. I would suggest you take a look at the HTML it ended up producing. The 'span' is the name of the tag that is used to wrap the word.

Anyway, without seeing the code, I suspect that the issue with your site is that somewhere, SPAN tags got re-defined as block containers instead of inline containers. I am just guessing but you might want to try adding something like this to the CSS in order to override this for the .highlight style:

    span.highlight {
        display: inline;
    }

You might also need to adjust the margins or paddings.

    span.highlight {
        display: inline;
        margin: 0;
        padding: 0;
    }

Unless you also have a highlight class defined in your site, this should fix your problem without affecting the rest of the site. If it does affect another part of your site, you might want to change the name of the class to eliminate the conflict.

Hope this helps.

Michael Milette
